### DISCUSSION TITLE
docker-composeでdown / up -dしたら42P01というエラーが出るようになった

### DISCUSSION THREAD

**Discussion by TenTakano** [misskey-dev/misskey#13099] [Q&A] [answered]
misskeyサーバーを運用していて、docker networkの構成を変更するため、docker-compose.ymlからリバースプロキシを削除して`docker-compose down`の後`docker-compose up -d`したところ、42P01というエラーが表示されて正常に起動できなくなってしまいました。

docker-composeファイルとしては以下です。
今回行った作業としては、リバースプロキシをmisskeyのdocker-compose.ymlから切り離して別サービス化するというもので、misskey自体には何も変更を加えていません。

変更前

```
version: "3"

services:
  nginx:
    restart: always
    links:
      - web
    image: nginx
    ports:
      - 443:443
    networks:
      - external_network
    volumes:
      - /home/misskey/nginx/conf.d:/etc/nginx/conf.d
      - /home/misskey/nginx/ssl:/etc/nginx/ssl
  web:
    build: .
    restart: always
    links:
      - db
      - redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal_network
      - external_network
    volumes:
      - /home/misskey/data/misskey/.config:/misskey/.config:ro

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - /home/misskey/data/redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  postgres:
    restart: always
    image: postgres:15-alpine
    networks:
      - internal_network
    env_file:
      - .config/docker.env
    volumes:
      - /home/misskey/data/postgres:/var/lib/postgres/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

networks:
  internal_network:
    internal: true
  external_network:
```

変更後

```
version: "3"

services:
  web:
    build: .
    restart: always
    links:
      - postgres
      - redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal_network
      - shared_network
    volumes:
      - /home/misskey/data/misskey/.config:/misskey/.config:ro

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - /home/misskey/data/redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  postgres:
    restart: always
    image: postgres:15-alpine
    networks:
      - internal_network
    env_file:
      - .config/docker.env
    volumes:
      - /home/misskey/data/postgres:/var/lib/postgres/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

networks:
  internal_network:
    internal: true
  shared_network:
    external: true
```

dockerのログを見ると、データベース不整合を起こしてしまっているようです。

```
postgres_1  | 2024-01-28 02:54:21.910 UTC [443754] ERROR:  relation "meta" does not exist at character 3978
postgres_1  | 2024-01-28 02:54:21.910 UTC [443754] STATEMENT:  SELECT "Meta"."id" AS "Meta_id", "Meta"."name" AS "Meta_name", "Meta"."description" AS "Meta_description", "Meta"."maintainerName" AS "Meta_maintainerName", "Meta"."maintainerEmail" AS "Meta_maintainerEmail", "Meta"."disableRegistration" AS "Meta_disableRegistration", "Meta"."langs" AS "Meta_langs", "Meta"."pinnedUsers" AS "Meta_pinnedUsers", "Meta"."hiddenTags" AS "Meta_hiddenTags", "Meta"."blockedHosts" AS "Meta_blockedHosts", "Meta"."sensitiveWords" AS "Meta_sensitiveWords", "Meta"."themeColor" AS "Meta_themeColor", "Meta"."mascotImageUrl" AS "Meta_mascotImageUrl", "Meta"."bannerUrl" AS "Meta_bannerUrl", "Meta"."backgroundImageUrl" AS "Meta_backgroundImageUrl", "Meta"."logoImageUrl" AS "Meta_logoImageUrl", "Meta"."iconUrl" AS "Meta_iconUrl", "Meta"."serverErrorImageUrl" AS "Meta_serverErrorImageUrl", "Meta"."notFoundImageUrl" AS "Meta_notFoundImageUrl", "Meta"."infoImageUrl" AS "Meta_infoImageUrl", "Meta"."cacheRemoteFiles" AS "Meta_cacheRemoteFiles", "Meta"."proxyAccountId" AS "Meta_proxyAccountId", "Meta"."emailRequiredForSignup" AS "Meta_emailRequiredForSignup", "Meta"."enableHcaptcha" AS "Meta_enableHcaptcha", "Meta"."hcaptchaSiteKey" AS "Meta_hcaptchaSiteKey", "Meta"."hcaptchaSecretKey" AS "Meta_hcaptchaSecretKey", "Meta"."enableRecaptcha" AS "Meta_enableRecaptcha", "Meta"."recaptchaSiteKey" AS "Meta_recaptchaSiteKey", "Meta"."recaptchaSecretKey" AS "Meta_recaptchaSecretKey", "Meta"."enableTurnstile" AS "Meta_enableTurnstile", "Meta"."turnstileSiteKey" AS "Meta_turnstileSiteKey", "Meta"."turnstileSecretKey" AS "Meta_turnstileSecretKey", "Meta"."sensitiveMediaDetection" AS "Meta_sensitiveMediaDetection", "Meta"."sensitiveMediaDetectionSensitivity" AS "Meta_sensitiveMediaDetectionSensitivity", "Meta"."setSensitiveFlagAutomatically" AS "Meta_setSensitiveFlagAutomatically", "Meta"."enableSensitiveMediaDetectionForVideos" AS "Meta_enableSensitiveMediaDetectionForVideos", "Meta"."summalyProxy" AS "Meta_summalyProxy", "Meta"."enableEmail" AS "Meta_enableEmail", "Meta"."email" AS "Meta_email", "Meta"."smtpSecure" AS "Meta_smtpSecure", "Meta"."smtpHost" AS "Meta_smtpHost", "Meta"."smtpPort" AS "Meta_smtpPort", "Meta"."smtpUser" AS "Meta_smtpUser", "Meta"."smtpPass" AS "Meta_smtpPass", "Meta"."enableServiceWorker" AS "Meta_enableServiceWorker", "Meta"."swPublicKey" AS "Meta_swPublicKey", "Meta"."swPrivateKey" AS "Meta_swPrivateKey", "Meta"."deeplAuthKey" AS "Meta_deeplAuthKey", "Meta"."deeplIsPro" AS "Meta_deeplIsPro", "Meta"."termsOfServiceUrl" AS "Meta_termsOfServiceUrl", "Meta"."repositoryUrl" AS "Meta_repositoryUrl", "Meta"."feedbackUrl" AS "Meta_feedbackUrl", "Meta"."defaultLightTheme" AS "Meta_defaultLightTheme", "Meta"."defaultDarkTheme" AS "Meta_defaultDarkTheme", "Meta"."useObjectStorage" AS "Meta_useObjectStorage", "Meta"."objectStorageBucket" AS "Meta_objectStorageBucket", "Meta"."objectStoragePrefix" AS "Meta_objectStoragePrefix", "Meta"."objectStorageBaseUrl" AS "Meta_objectStorageBaseUrl", "Meta"."objectStorageEndpoint" AS "Meta_objectStorageEndpoint", "Meta"."objectStorageRegion" AS "Meta_objectStorageRegion", "Meta"."objectStorageAccessKey" AS "Meta_objectStorageAccessKey", "Meta"."objectStorageSecretKey" AS "Meta_objectStorageSecretKey", "Meta"."objectStoragePort" AS "Meta_objectStoragePort", "Meta"."objectStorageUseSSL" AS "Meta_objectStorageUseSSL", "Meta"."objectStorageUseProxy" AS "Meta_objectStorageUseProxy", "Meta"."objectStorageSetPublicRead" AS "Meta_objectStorageSetPublicRead", "Meta"."objectStorageS3ForcePathStyle" AS "Meta_objectStorageS3ForcePathStyle", "Meta"."enableIpLogging" AS "Meta_enableIpLogging", "Meta"."enableActiveEmailValidation" AS "Meta_enableActiveEmailValidation", "Meta"."enableChartsForRemoteUser" AS "Meta_enableChartsForRemoteUser", "Meta"."enableChartsForFederatedInstances" AS "Meta_enableChartsForFederatedInstances", "Meta"."policies" AS "Meta_policies", "Meta"."serverRules" AS "Meta_serverRules", "Meta"."preservedUsernames" AS "Meta_preservedUsernames" FROM "meta" "Meta" ORDER BY "Meta"."id" DESC
web_1       | WARN 1    [queue inbox]   failed(QueryFailedError: relation "meta" does not exist) id=611465 attempts=8/8 age=260m activity=https://misskey.io/likes/9p07p7952vd50a6a
web_1       | WARN 1    [queue inbox]   failed(QueryFailedError: relation "meta" does not exist) id=611851 attempts=6/8 age=60m activity=https://misskey.io/notes/9p0eu4h3jnug0iw1/activity
web_1       | WARN 1    [queue inbox]   failed(QueryFailedError: relation "meta" does not exist) id=611721 attempts=7/8 age=129m activity=https://misskey.io/notes/9p0cdnrajnug0c8p/activity
web_1       | WARN 1    [queue inbox]   failed(QueryFailedError: relation "meta" does not exist) id=611841 attempts=6/8 age=66m activity=https://misskey.io/likes/9p0enjhh1v6l019n
web_1       | WARN 1    [queue inbox]   failed(QueryFailedError: relation "meta" does not exist) id=611848 attempts=6/8 age=65m activity=https://misskey.io/likes/9p0eo7dljnug0ig4
web_1       | WARN 1    [queue inbox]   failed(QueryFailedError: relation "meta" does not exist) id=611711 attempts=7/8 age=136m activity=https://misskey.io/notes/9p0c5yomit1k073c/activity
web_1       | WARN 1    [queue inbox]   failed(QueryFailedError: relation "meta" does not exist) id=611409 attempts=8/8 age=283m activity=https://misskey.io/likes/9p06wgcek00w08fa
web_1       | WARN 1    [queue inbox]   failed(QueryFailedError: relation "meta" does not exist) id=611731 attempts=7/8 age=127m activity=https://misskey.io/likes/9p0chv93jnug0cko
web_1       | WARN 1    [queue inbox]   failed(QueryFailedError: relation "meta" does not exist) id=611707 attempts=7/8 age=138m activity=https://misskey.io/notes/9p0c3njjit1k06v6/activity
web_1       | WARN 1    [queue inbox]   failed(QueryFailedError: relation "meta" does not exist) id=611719 attempts=7/8 age=130m activity=https://misskey.io/notes/9p0cdhz37sv7079w/activity
```

また、使用しているmisskey, 環境は以下の通りです。

- misskey: tag: 13.13.2
- ホストOS: Ubuntu 20.04 LTS

どなたかお分かりになる方、アドバイスを頂けると助かります。
よろしくお願いいたします。
