### DISCUSSION TITLE
Migrating from docker build to docker hub premade image on another server

### DISCUSSION THREAD

**Discussion by Albirew** [misskey-dev/misskey#14479] [Show and tell]
Here's my situation:
I'd like to migrate my misskey instance to another server.
By looking on the web, i saw a docker hub image existed ([misskey/misskey:latest](https://hub.docker.com/r/misskey/misskey) found [here](https://github.com/joinmisskey/bash-install/blob/main/ubuntu.sh#L127))

I was wondering if, when migrating, i could use the docker hub image instead of having to rebuild everything at each release.
I'm sure it's possible, i mean, it's just 1 line to change on docker-compose.yml (replace build line with image)
so i tried:
- i copied only ./{files,.config,redis,db}/
- i edited docker-compose.yml like this:
```yml
services:
  web:
    image: misskey/misskey:latest
    restart: always
    links:
      - db
      - redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - internal_network
      - external_network
    volumes:
      - ./files:/misskey/files
      - ./.config:/misskey/.config:ro

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: postgres:15-alpine
    networks:
      - internal_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

networks:
  internal_network:
    internal: true
  external_network:
```
and am now waiting for the megafolder ./files (seriously, why 1214564 files of 300+Gb in ./files for a single user instance where "drive" only have 50 files with total of 10mb used?) to finish the transfer between servers and start it.
