### DISCUSSION TITLE
How to install misskey in Synology docker?

### DISCUSSION THREAD

**Discussion by zhengfan2014** [misskey-dev/misskey#6987] [Q&A]
English Version:
hello ,I am a newbie, and I encountered a problem in deploying misskey. When I run misskey docker, the container will stop running. Does anyone deploy misskey on Synology’s docker? I hope to share experience with us rookies
Thanks 🙏

日本語版:
私は初心者ですが、ミスキーの展開で問題が発生しました。ミスキードッカーを実行すると、コンテナーの実行が停止します。Synologyのドッカーにミスキーを展開する人はいますか？ルーキーと経験を共有できれば幸いです。ありがとう🙏

简体中文:
我是新手，我在部署misskey遇到了问题，当我运行misskey docker时容器会停止运行，有没有人在群晖的docker上部署misskey，希望可以向我们这些菜鸟分享经验。谢谢🙏

**Comment by rinsuki** [comment]
do you have a error log?

**Reply by zhengfan2014** [reply]
yes,there

date | stream | content
-- | -- | --
2020-12-17 02:39:18 | stdout | 
2020-12-17 02:39:18 | stdout | npm ERR!     /root/.npm/_logs/2020-12-17T02_39_18_280Z-debug.log
2020-12-17 02:39:18 | stdout | npm ERR! A complete log of this run can be found in:
2020-12-17 02:39:18 | stdout | 
2020-12-17 02:39:18 | stdout | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-12-17 02:39:18 | stdout | npm ERR! Failed at the misskey@12.55.0 migrateandstart script.
2020-12-17 02:39:18 | stdout | npm ERR!
2020-12-17 02:39:18 | stdout | npm ERR! Exit status 1
2020-12-17 02:39:18 | stdout | npm ERR! misskey@12.55.0 migrateandstart: `npm run migrate && npm run start`
2020-12-17 02:39:18 | stdout | npm ERR! errno 1
2020-12-17 02:39:18 | stdout | npm ERR! code ELIFECYCLE
2020-12-17 02:39:18 | stdout | npm ERR!     /root/.npm/_logs/2020-12-17T02_39_18_213Z-debug.log
2020-12-17 02:39:18 | stdout | npm ERR! A complete log of this run can be found in:
2020-12-17 02:39:18 | stdout | 
2020-12-17 02:39:18 | stdout | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-12-17 02:39:18 | stdout | npm ERR! Failed at the misskey@12.55.0 migrate script.
2020-12-17 02:39:18 | stdout | npm ERR!
2020-12-17 02:39:18 | stdout | npm ERR! Exit status 1
2020-12-17 02:39:18 | stdout | npm ERR! misskey@12.55.0 migrate: `ts-node ./node_modules/typeorm/cli.js migration:run`
2020-12-17 02:39:18 | stdout | npm ERR! errno 1
2020-12-17 02:39:18 | stdout | npm ERR! code ELIFECYCLE
2020-12-17 02:39:18 | stdout | }
2020-12-17 02:39:18 | stdout | path: '/misskey/built/config/../../.config/default.yml'
2020-12-17 02:39:18 | stdout | code: 'ENOENT',
2020-12-17 02:39:18 | stdout | syscall: 'open',
2020-12-17 02:39:18 | stdout | errno: -2,
2020-12-17 02:39:18 | stdout |     at Function.Module._load (internal/modules/cjs/loader.js:937:14) {
2020-12-17 02:39:18 | stdout |     at Module.load (internal/modules/cjs/loader.js:1049:32)
2020-12-17 02:39:18 | stdout | at Object.require.extensions.<computed> [as .js] (/misskey/node_modules/ts-node/src/index.ts:1046:12)
2020-12-17 02:39:18 | stdout |     at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
2020-12-17 02:39:18 | stdout | at Module.m._compile (/misskey/node_modules/ts-node/src/index.ts:1043:23)
2020-12-17 02:39:18 | stdout |     at Module._compile (internal/modules/cjs/loader.js:1200:30)
2020-12-17 02:39:18 | stdout | at Object.<anonymous> (/misskey/built/config/index.js:4:33)
2020-12-17 02:39:18 | stdout | at Object.load [as default] (/misskey/built/config/load.js:20:37)
2020-12-17 02:39:18 | stdout |     at Object.readFileSync (fs.js:364:35)
2020-12-17 02:39:18 | stdout |     at Object.openSync (fs.js:461:3)
2020-12-17 02:39:18 | stdout | Error: ENOENT: no such file or directory, open '/misskey/built/config/../../.config/default.yml'
2020-12-17 02:39:17 | stdout | Error during migration run:
2020-12-17 02:39:00 | stdout |  
2020-12-17 02:39:00 | stdout | > ts-node ./node_modules/typeorm/cli.js migration:run
2020-12-17 02:39:00 | stdout | > misskey@12.55.0 migrate /misskey
2020-12-17 02:39:00 | stdout |  
2020-12-17 02:38:59 | stdout |  
2020-12-17 02:38:59 | stdout | > npm run migrate && npm run start
2020-12-17 02:38:59 | stdout | > misskey@12.55.0 migrateandstart /misskey
2020-12-17 02:38:59 | stdout |

**Reply by rinsuki** [reply]
I don't know how mount folder to container in Synergy NAS, but you should write config file and mount config folder to `/misskey/.config` of container.

**Reply by zhengfan2014** [reply]
> I don't know how mount folder to container in Synergy NAS, but you should write config file and mount config folder to `/misskey/.config` of container.

I created default.yml and docker.env according to the requirements of the document. And map the config folder of Synology to /misskey/.config. But starting the docker container still stops running

docker.env
```
# db settings
POSTGRES_PASSWORD=r8Ry2Yb8mibBOMZ5
POSTGRES_USER=misskey
POSTGRES_DB=misskey
```

default.yml
```
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Misskey configuration
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

#   ┌─────┐
#───┘ URL └─────────────────────────────────────────────────────

# Final accessible URL seen by a user.
url: http://192.168.0.165:3000/

# ONCE YOU HAVE STARTED THE INSTANCE, DO NOT CHANGE THE
# URL SETTINGS AFTER THAT!

#   ┌───────────────────────┐
#───┘ Port and TLS settings └───────────────────────────────────

#
# Misskey supports two deployment options for public.
#

# Option 1: With Reverse Proxy
#
#                 +----- https://example.tld/ ------------+
#   +------+      |+-------------+      +----------------+|
#   | User | ---> || Proxy (443) | ---> | Misskey (3000) ||
#   +------+      |+-------------+      +----------------+|
#                 +---------------------------------------+
#
#   You need to setup reverse proxy. (eg. nginx)
#   You do not define 'https' section.

# Option 2: Standalone
#
#                 +- https://example.tld/ -+
#   +------+      |   +---------------+    |
#   | User | ---> |   | Misskey (443) |    |
#   +------+      |   +---------------+    |
#                 +------------------------+
#
#   You need to run Misskey as root.
#   You need to set Certificate in 'https' section.

# To use option 1, uncomment below line.
#port: 3000    # A port that your Misskey server should listen.

# To use option 2, uncomment below lines.
#port: 443

#https:
#  # path for certification
#  key: /etc/letsencrypt/live/example.tld/privkey.pem
#  cert: /etc/letsencrypt/live/example.tld/fullchain.pem

#   ┌──────────────────────────┐
#───┘ PostgreSQL configuration └────────────────────────────────

db:
  host: 192.168.0.165
  port: 3307

  # Database name
  db: misskey

  # Auth
  user: misskey
  pass: r8Ry2Yb8mibBOMZ5

  # Whether disable Caching queries
  #disableCache: true

  # Extra Connection options
  #extra:
  #  ssl: true

#   ┌─────────────────────┐
#───┘ Redis configuration └─────────────────────────────────────

redis:
  host: localhost
  port: 6379
  #pass: example-pass
  #prefix: example-prefix
  #db: 1

#   ┌─────────────────────────────┐
#───┘ Elasticsearch configuration └─────────────────────────────

#elasticsearch:
#  host: localhost
#  port: 9200
#  ssl: false
#  user: 
#  pass: 

#   ┌───────────────┐
#───┘ ID generation └───────────────────────────────────────────

# You can select the ID generation method.
# You don't usually need to change this setting, but you can
# change it according to your preferences.

# Available methods:
# aid ... Short, Millisecond accuracy
# meid ... Similar to ObjectID, Millisecond accuracy
# ulid ... Millisecond accuracy
# objectid ... This is left for backward compatibility

# ONCE YOU HAVE STARTED THE INSTANCE, DO NOT CHANGE THE
# ID SETTINGS AFTER THAT!

id: 'aid'

#   ┌─────────────────────┐
#───┘ Other configuration └─────────────────────────────────────

# Whether disable HSTS
#disableHsts: true

# Number of worker processes
#clusterLimit: 1

# Job concurrency per worker
# deliverJobConcurrency: 128
# inboxJobConcurrency: 16

# Job rate limiter
# deliverJobPerSec: 128
# inboxJobPerSec: 16

# Job attempts
# deliverJobMaxAttempts: 12
# inboxJobMaxAttempts: 8

# IP address family used for outgoing request (ipv4, ipv6 or dual)
#outgoingAddressFamily: ipv4

# Syslog option
#syslog:
#  host: localhost
#  port: 514

# Proxy for HTTP/HTTPS
#proxy: http://127.0.0.1:3128

#proxyBypassHosts: [
#  'example.com',
#  '192.0.2.8'
#]

# Proxy for SMTP/SMTPS
#proxySmtp: http://127.0.0.1:3128   # use HTTP/1.1 CONNECT
#proxySmtp: socks4://127.0.0.1:1080 # use SOCKS4
#proxySmtp: socks5://127.0.0.1:1080 # use SOCKS5

# Media Proxy
#mediaProxy: https://example.com/proxy

# Sign to ActivityPub GET request (default: false)
#signToActivityPubGet: true
```

docker log
```
date | stream | content
-- | -- | --
2020-12-17 03:08:18 | stdout |  
2020-12-17 03:08:18 | stdout |   npm    ERR!        /root/.npm/_logs/2020-12-17T03_08_18_628Z-debug.log
2020-12-17 03:08:18 | stdout |  npm    ERR!    A complete log of this run can be found in:
2020-12-17 03:08:18 | stdout |  
2020-12-17 03:08:18 | stdout |   npm    ERR!    This is probably not a problem with npm. There is likely additional logging output above.
2020-12-17 03:08:18 | stdout |   npm    ERR!    Failed at the misskey@12.55.0 migrateandstart script.
2020-12-17 03:08:18 | stdout |   npm    ERR!   
2020-12-17 03:08:18 | stdout |   npm    ERR!    Exit status 1
2020-12-17 03:08:18 | stdout |   npm    ERR!    misskey@12.55.0 migrateandstart: `npm run migrate && npm run start`
2020-12-17 03:08:18 | stdout |   npm    ERR!    errno  1
2020-12-17 03:08:18 | stdout |   npm    ERR!    code  ELIFECYCLE
2020-12-17 03:08:18 | stdout |   npm    ERR!        /root/.npm/_logs/2020-12-17T03_08_18_564Z-debug.log
2020-12-17 03:08:18 | stdout |  npm    ERR!    A complete log of this run can be found in:
2020-12-17 03:08:18 | stdout |  
2020-12-17 03:08:18 | stdout |   npm    ERR!    This is probably not a problem with npm. There is likely additional logging output above.
2020-12-17 03:08:18 | stdout |   npm    ERR!    Failed at the misskey@12.55.0 migrate script.
2020-12-17 03:08:18 | stdout |   npm    ERR!   
2020-12-17 03:08:18 | stdout |   npm    ERR!    Exit status 1
2020-12-17 03:08:18 | stdout |   npm    ERR!    misskey@12.55.0 migrate: `ts-node ./node_modules/typeorm/cli.js migration:run`
2020-12-17 03:08:18 | stdout |   npm    ERR!    errno  1
2020-12-17 03:08:18 | stdout |  npm    ERR!    code  ELIFECYCLE
2020-12-17 03:08:18 | stdout | at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
2020-12-17 03:08:18 | stdout | at Socket.Readable.push (_stream_readable.js:217:10)
2020-12-17 03:08:18 | stdout | at readableAddChunk (_stream_readable.js:278:9)
2020-12-17 03:08:18 | stdout | at addChunk (_stream_readable.js:302:12)
2020-12-17 03:08:18 | stdout | at Socket.EventEmitter.emit (domain.js:485:12)
2020-12-17 03:08:18 | stdout | at Socket.emit (events.js:315:20)
2020-12-17 03:08:18 | stdout | at Socket.<anonymous> (/misskey/node_modules/pg-protocol/src/index.ts:7:48)
2020-12-17 03:08:18 | stdout | at Parser.parse (/misskey/node_modules/pg-protocol/src/parser.ts:101:30)
2020-12-17 03:08:18 | stdout | at Parser.handlePacket (/misskey/node_modules/pg-protocol/src/parser.ts:198:16)
2020-12-17 03:08:18 | stdout | AssertionError [ERR_ASSERTION]: unknown message code: 58
2020-12-17 03:08:18 | stdout | ^
2020-12-17 03:08:18 | stdout | assert.fail(`unknown message code: ${code.toString(16)}`)
2020-12-17 03:08:18 | stdout | /misskey/node_modules/pg-protocol/src/parser.ts:198
2020-12-17 03:08:18 | stdout |  
2020-12-17 03:07:31 | stdout |  
2020-12-17 03:07:31 | stdout | > ts-node ./node_modules/typeorm/cli.js migration:run
2020-12-17 03:07:31 | stdout | > misskey@12.55.0 migrate /misskey
2020-12-17 03:07:31 | stdout |  
2020-12-17 03:07:30 | stdout |  
2020-12-17 03:07:30 | stdout | > npm run migrate && npm run start
2020-12-17 03:07:30 | stdout | > misskey@12.55.0 migrateandstart /misskey
2020-12-17 03:07:30 | stdout
```
