### DISCUSSION TITLE
How to access the pgsql database in the docker container?

### DISCUSSION THREAD

**Discussion by mitian233** [misskey-dev/misskey#9212] [Q&A] [answered]
I deployed misskey using docker. But I get the error when I try to manage the database with pgAdmin. It can't connect the database server. After i check the docker processes I found that the pgsql container has no open ports for pgAdmin to connect. 

```plaintext
CONTAINER ID   IMAGE                  COMMAND                  CREATED        STATUS        PORTS                                            NAMES
------------   misskey_web            "/usr/bin/tini -- np…"   21 hours ago   Up 2 hours    0.0.0.0:3000->3000/tcp, :::3000->3000/tcp        misskey-web-1
------------   postgres:12.2-alpine   "docker-entrypoint.s…"   21 hours ago   Up 2 hours                                                     misskey-db-1
------------   redis:4.0-alpine       "docker-entrypoint.s…"   44 hours ago   Up 2 hours                                                     misskey-redis-1
```

How to make the pgAdmin connect to the local database?

**Comment by tecoholic** [comment, marked as answer]
There are 2 ways to do it. 

1. Add a `ports` mapping to the Postgres service on `docker-compose.yml` and open the port to the host and connect from the host
2. Add PgAdmin to the `docker-compose.yml` and link it to the postgres container.

For option one you would do something like the following and and connect to it from pgadmin using "localhost:5432"

```diff
  db:
    restart: always
    image: postgres:12.2-alpine
    networks:
      - internal_network
+    - external_network
+  ports:
+    - "5432:5432" 
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
```

For option 2, you will have to add a new section like

```yaml
  pdadmin:
    image: dpage/pgadmin4
    networks:
      - internal_network
      - external_network
    ports:
      - "8080:80" # to expose the pgadmin to your local machine
    env:
      - PGADMIN_DEFAULT_EMAIL=<your-email>
      - PGADMIN_DEFFAULT_PASSWORD=<you_password>
    links:
      - db
 ```

Then you can open pg admin from "localhost:8080" and connect to the DB from pgadmin using "db:5432".
