### ISSUE TITLE
Infinite «Reconnecting» after login.

### ISSUE THREAD

**Issue by bttmchnd** [misskey-dev/misskey#1934]
Hi.

I'm trying to build-up a new instance of Misskey, but have an issue.

At first, what have I done. Following the installation guide, I set up the database, cloned the repository and checked out the latest release. The final configuration looks like:
```
name: Ministry of Moonbutt Science
description: 'Who said «Fallout: Equestria»?!'

maintainer:
  name: commagray
  url: mailto://commagray@sunbutt.faith
  repository_url: https://github.com/syuilo/misskey
  feedback_url: https://github.com/syuilo/misskey/issues

url: 'https://ministry.moonbutt.science'

port: 9584

mongodb:
  host: something
  port: 27017
  db: something
  user: something
  pass: something

redis:
  host: something
  port: 6379
  pass: something

preventCache: false

https:
  key: correct path and permissions to
  cert: correct path and permissions to
```
And, as usual, I set up the reverse proxy with Nginx:
```
server {
                listen 443 ssl;
                ssl_certificate correct path and permissions to;
                ssl_certificate_key correct path and permissions to;
                ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
                server_name ministry.moonbutt.science;
                location / {
                        proxy_pass https://localhost:9584;
                }
        }

```
Аfter that I can go to https://ministry.moonbutt.faith, I can register an account, but after login everything is trying to reconnect to something. Screenshot:
![screenshot from 2018-07-20 14-37-59](https://user-images.githubusercontent.com/27947961/43002095-34db213c-8c30-11e8-8802-a8daadd378b2.png)
(Chromium, development build.)
So I can't do anything with front-end: to post, to follow, to see someone's timeline — everything is «reconnecting». But federation seems to be working: I can paste someone's ID and see their profile, but not the timeline.

Thanks.
