### ISSUE TITLE
Accept activities do not mention the identifier of the accepted Follow activity

### ISSUE THREAD

**Issue by ClearlyClaire** [misskey-dev/misskey#2812]
The `object` attribute of `Accept` activities do not include the object's id, although object identifiers are mandatory unless the object is intended to be transient.

**Comment by mei23** [comment]
Probably means...
```yml
# Receilved Follow Activity
id    : https://1.example.com/follow1
type  : Follow
actor : https://1.example.com/users/1
object: https://2.example.com/users/2

# Accept Activity from Misskey
id    : https://2.example.com/accept1
type  : Accept
actor : https://2.example.com/users/2
object:
  id    : https://1.example.com/follow1 # <= Missing (expects same as Follow's one)
  type  : Follow
  actor : https://1.example.com/users/1
  object: https://2.example.com/users/2
```
