### ISSUE TITLE
502 Bad Requset

### ISSUE THREAD

**Issue by Never2333** [misskey-dev/misskey#3222]
Hello, I am new to here.
When I finish my installation, and open the website, it said error 502.
I tried to reboot the VPN and reload the mirror, but the issues is still going on.

**Comment by syuilo** [comment]
Thank you for your reporting.
Are you using Nginx? :)

**Comment by Never2333** [comment]
Yes

**Comment by syuilo** [comment]
ok thanks. Please show me your configuration of Misskey and nginx.

**Comment by Never2333** [comment]
Okay, but could you please wait for a while, I am having dinner, sorry.

**Comment by Never2333** [comment]
```yaml
name: example-instance-name # Name of your instance
description: example-description # Description of your instance

maintainer:
  name: example-maitainer-name # Your name
  url: http://example.com/ # Your contact (http or mailto)

# Final accessible URL seen by a user.
url: https://misskey.never666.com/

# port: 3000    # A port that your Misskey server should listen.

mongodb:
  host: localhost
  port: 27017
  db: misskey
  user: misskey
  pass: 6631330Zhang

redis:
  host: localhost
  port: 6379
  pass: example-pass
```

**Comment by Never2333** [comment]
```
ap $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

server {
    listen       80;
    listen       443 ssl http2;
    server_name  misskey.never666.com misskey.never666.com;
    client_max_body_size 100m;
    client_body_buffer_size 2048k;
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }

    ssl_certificate    /etc/letsencrypt/live/misskey.never666.com/fullchain.pem;
    ssl_certificate_key    /etc/letsencrypt/live/misskey.never666.com/privkey.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;

location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";
    proxy_pass_header Server;

    proxy_pass http://127.0.0.1:3000;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    tcp_nodelay on;
  }
}
```

**Comment by Never2333** [comment]
I use CentOS 7.4 X64

**Comment by syuilo** [comment]
Thank you.
I think you need to uncomment the setting of the port.

``` yaml
# port: 3000    # A port that your Misskey server should listen.
```
to
``` yaml
port: 3000    # A port that your Misskey server should listen.
```

**Comment by Never2333** [comment]
Oh, I am going to try it. Thank you very much!

**Comment by syuilo** [comment]
Good luck!

**Comment by syuilo** [comment]
Can you launch Misskey without Nginx?

**Comment by Never2333** [comment]
emmm How to do it?

**Comment by syuilo** [comment]
Please write config as:
``` yml
port: 443

https:
  key: /etc/letsencrypt/live/misskey.never666.com/privkey.pem
  cert: /etc/letsencrypt/live/misskey.never666.com/fullchain.pem
```

**Comment by Never2333** [comment]
The misskey config?

**Comment by syuilo** [comment]
yes

**Comment by Never2333** [comment]
```yaml
name: example-instance-name # Name of your instance
description: example-description # Description of your instance

maintainer:
  name: Never # Your name
  url: http://never666.com/ # Your contact (http or mailto)

# Final accessible URL seen by a user.
url: https://misskey.never666.com/

  port: 3000    # A port that your Misskey server should listen.

port: 443

https:
  key: /etc/letsencrypt/live/misskey.never666.com/privkey.pem
  cert: /etc/letsencrypt/live/misskey.never666.com/fullchain.pem

mongodb:
  host: localhost
  port: 27017
  db: misskey
  user: misskey
  pass: example-pass

redis:
  host: localhost
  port: 6379
  pass: examle-pass
```
