### ISSUE TITLE
リアクションのアニメーション多様化

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#3643]
新アニメーションを見て、 😇 が昇天するのはうまいなと思ったが、それ以外はそれぞれ合ったリアクションがあったら良いなと思った

怒りなら、 `***hoge***` 構文みたいに揺れる
寿司やプリンはぷるぷる
笑いはクルクル回る
👍 は上下に動く

といったのはいかがだろうか？

**Comment by EbiseLutica** [comment]
👍 上下揺れ
❤ 脈動する感じ
😆 左右傾き
🤔 右にゆっくり傾いて、戻る
😮 大っきくなってすぐ戻る
🎉 ジャンプ+大きくなって戻る
💢 暴れる
😥 下にいって戻ってくる
😇 昇天
🍮 ぷるんぷるん
🍣 360度回転する

どう？

**Comment by acid-chicken** [comment]
> 🍣 360度回転する

どういった意図による演出ですか？

**Comment by EbiseLutica** [comment]
回転寿司です　代案ありますか？

**Comment by acid-chicken** [comment]
こんなのはどうでしょう。

```css
.sushi::before,
.sushi::after {
  content: '🍣';
  display: inline-block;
  position: absolute }

.sushi::before {
  animation: sushi-in 1s cubic-bezier(.55, .06, .68, .19) infinite;
  transform-origin: left }

@keyframes sushi-in
{
  0%   { transform: rotateY(.25turn) }
  50%  { transform: rotateY(.25turn) }
  100% { transform: rotateY(0) }
}

.sushi::after {
  animation: sushi-out 1s cubic-bezier(.22, .61, .36, 1) infinite;
  transform-origin: right }

@keyframes sushi-out
{
  0%   { transform: rotateY(0) }
  50%  { transform: rotateY(.25turn) }
  100% { transform: rotateY(.25turn) }
}
```
