### ISSUE TITLE
[10.82.3]"You need to configure the minio bucket."がログに出力されて起動しない

### ISSUE THREAD

**Issue by khws4v1** [misskey-dev/misskey#4179]
# Summary

Misskeyを10.82.0から10.82.3にアップデートしたところ、`You need to configure the minio bucket.`とログに出力されてMisskeyが起動できなくなりました。

ログ(一部抜粋)
```
web_1    | /misskey/built/config/load.js:62
web_1    |             throw 'You need to configure the minio bucket.';
web_1    |             ^
web_1    | You need to configure the minio bucket.
web_1    | npm ERR! code ELIFECYCLE
web_1    | npm ERR! errno 1
web_1    | npm ERR! misskey@10.82.3 start: `node ./index.js`
web_1    | npm ERR! Exit status 1
web_1    | npm ERR! 
web_1    | npm ERR! Failed at the misskey@10.82.3 start script.
web_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
web_1    | 
web_1    | npm ERR! A complete log of this run can be found in:
web_1    | npm ERR!     /root/.npm/_logs/2019-02-07T10_05_43_223Z-debug.log
web_1    | 
web_1    | > misskey@10.82.3 start /misskey
web_1    | > node ./index.js
```

[このコミット](https://github.com/syuilo/misskey/commit/96bc17aa1014983d5e6bf8b4c05d898156995a0d)のCIのテストでも同様のエラーが発生しており、関係があるものと思われます。

https://circleci.com/gh/syuilo/misskey/7656?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://circleci.com/gh/syuilo/misskey/7655?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

10.82.3にアップデートした後、前のバージョンである10.82.2にダウングレードしたところ正常に起動しました。

# Expected Behavior

Misskeyが起動すること。

# Actual Behavior

Misskeyが起動しない。

# Steps to Reproduce

不明

# Environment

Misskey 10.82.3 (with Docker)

**Comment by khws4v1** [comment]
#4170

**Comment by acid-chicken** [comment]
@khws4v1 Envlronmentの項をもう少し詳しく書いていただくことは可能ですか？主にストレージ周りの構成を知りたいです。また、可能であればコンフィグのdrive項も見せてもらえると助かります。

ちなみにCIが落ちたのは 仕様変更に伴うコンフィグ更新を忘れていたためです。（なぜビルドが通ってないのにマージしたのかは理解不能。）

**Comment by khws4v1** [comment]
## ストレージ関係

オブジェクトストレージは同じサーバーのDockerコンテナ上で動作しているminioです。  
Misskey以外にもMastodon上からも使っており、正常に動作しています。

## `default.yml`

一部箇所は仮の値になっていますが、drive関係のdefault.ymlです。

```
drive:
#  storage: 'db'

  # OR

  storage: 'minio'
  bucket: misskey
  prefix: drive
  baseUrl: https://example.com/misskey
  config:
    endPoint: example.com
    port: 9000
    useSSL: false
    accessKey: XXXXXXXXXXXX
    secretKey: XXXXXXXXXXXX
```
