### ISSUE TITLE
"Error: unable to verify the first certificate"

### ISSUE THREAD

**Issue by skid9000** [misskey-dev/misskey#4774]
## 💡 Summary

I just updated our Misskey instance from last v10 to v11.2.2
Everything that need to do a network request server-side (except to get something from other instances) result to a "Error: unable to verify the first certificate".

## 🙂 Expected Behavior

It should just work 🤔 

## ☹️ Actual Behavior

"Error: unable to verify the first certificate"

For exemple :

"avril 23 17:53:54 mozuku misskey[93631]: ERR  4        [download-url]        Failed to start download: https://misskey.anjara.eu/files/f5922fe9-7390-4319-859e-7158dcbae708: Error: unable to verify the first certificate"

## 📝 Steps to Reproduce

1. Migrate last v10 tp v11.2.2
2. Start misskey
3. Try to produce a network request (for exemple just go to your profile and set a new banner or something).
4. See error in server logs

## 📌 Environment

Misskey v11.2.2
Node 11.11.0
Nginx reverse proxy (so no https misskey side).

**Comment by syuilo** [comment]
Thank you for reporting.
Can you show me your misskey configuration?

**Comment by skid9000** [comment]
Sure

```
# Misskey configuration
# Final accessible URL seen by a user.
url: https://misskey.anjara.eu

# To use option 1, uncomment below line.
port: 3123    # A port that your Misskey server should listen.

db:
  host: /var/run/postgresql

  # Database name
  db: misskey_prod

  # Auth
  user: misskey

redis:
  host: localhost
  port: 6379

drive:
  storage: 'fs'

id: 'meid'
autoAdmin: true
disableHsts: true
```
