### ISSUE TITLE
他のインスタンスのユーザーフォローできない問題

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#5536]
## 💡 Summary
- 他のインスタンスのユーザーフォローできません

## 🙂 Expected Behavior
- ビルド時にエラー出ないこと
- 正常にフォローなどできること

## ☹️ Actual Behavior
- docker image をビルドするときにエラーが出ましたが、ビルド成功扱いされました。
  - [ログ](https://github.com/syuilo/misskey/files/3753843/build_error.txt)(エラーは362行から)
- misskeyのインスタンスを建てました
- admin垢を作りました
- admin垢でpawooのユーザーをフォローしようとしたら失敗しました
- 検証のためもう一個userを作って、pawooのユーザーをフォローしようとしたら失敗しました
- しかしフォローしようとした他のインスタンスのユーザーが連合タイムラインに出ました

## 📝 Steps to Reproduce

- 基本dockerのsetup guideそのままやってました。
- docker-compose.ymlなどの変更はあります。
  - [docker-compose.yml](https://github.com/syuilo/misskey/issues/5536#issuecomment-544805175)
  - [docker.env](https://github.com/syuilo/misskey/issues/5536#issuecomment-544805254)
  - [default.yml](https://github.com/syuilo/misskey/issues/5536#issuecomment-544805334)

## 📌 Environment

- AWS EC2
  - Amazon Linux release 2 (Karoo)
  - Linux 4.14.146-119.123.amzn2.x86_64
- Docker
  - Docker version 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136

**Comment by ghost** [comment]
pawooのユーザーをフォローしようとしたときの挙動
```
2分前 [api] SLOW API CALL DETECTED: users/show (2667.1327270045877ms)
{
}
2分前 [queue.deliver] failed(Error: Missing process handler for job type __default__) id=1 to=https://pawoo.net/users/_moondoggie/inbox
{
"e": {
"name": "Error",
"stack": "Error: Missing process handler for job type __default__ at Queue.processJob (/misskey/node_modules/bull/lib/queue.js:1034:7) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:93:5)",
"message": "Missing process handler for job type __default__"
},
"job": {
"id": "1",
"data": {
"to": "https://pawoo.net/users/_moondoggie/inbox",
"user": {
"id": "7z4xm8yw1v",
"uri": null,
"host": null,
"name": null,
"tags": [
],
"inbox": null,
"isBot": false,
"isCat": false,
"token": "2Hw98d8KOCVR5v5g",
"emojis": [
],
"isAdmin": true,
"avatarId": null,
"bannerId": null,
"featured": null,
"isLocked": false,
"username": "admin",
"avatarUrl": null,
"bannerUrl": null,
"createdAt": "2019-10-22T04:47:40.520Z",
"updatedAt": null,
"isSilenced": false,
"notesCount": 0,
"avatarColor": null,
"bannerColor": null,
"isModerator": false,
"isSuspended": false,
"sharedInbox": null,
"lastFetchedAt": null,
"followersCount": 1,
"followingCount": 0
},
"content": {
"id": "https://misskey.nagaseyami.com/a399b4c7-3e7f-4baa-96ec-ea12680a8020",
"type": "Follow",
"actor": "https://misskey.nagaseyami.com/users/7z4xm8yw1v",
"object": "https://pawoo.net/users/_moondoggie",
"@context": [
"https://www.w3.org/ns/activitystreams",
"https://w3id.org/security/v1",
{
"Hashtag": "as:Hashtag"
}
]
}
},
"name": "__default__",
"opts": {
"delay": 0,
"backoff": {
"type": "exponential",
"delay": 60000
},
"attempts": 8,
"timestamp": 1571719795624,
"removeOnFail": true,
"removeOnComplete": true
},
"delay": 0,
"progress": 0,
"timestamp": 1571719795624,
"finishedOn": null,
"stacktrace": [
"Error: Missing process handler for job type __default__ at Queue.processJob (/misskey/node_modules/bull/lib/queue.js:1034:7) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:93:5)"
],
"processedOn": 1571719795629,
"returnvalue": null,
"attemptsMade": 1,
"failedReason": "Missing process handler for job type __default__"
}
}
```

**Comment by ghost** [comment]
syuiloさんをフォローしようとしたときの挙動
```
1分前 [api] SLOW API CALL DETECTED: users/show (1890.4327009990811ms)
{
}
1分前 [queue.deliver] failed(Error: Missing process handler for job type __default__) id=2 to=https://misskey.io/users/7rkrarq81i/inbox
{
"e": {
"name": "Error",
"stack": "Error: Missing process handler for job type __default__ at Queue.processJob (/misskey/node_modules/bull/lib/queue.js:1034:7) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:93:5)",
"message": "Missing process handler for job type __default__"
},
"job": {
"id": "2",
"data": {
"to": "https://misskey.io/users/7rkrarq81i/inbox",
"user": {
"id": "7z4xm8yw1v",
"uri": null,
"host": null,
"name": null,
"tags": [
],
"inbox": null,
"isBot": false,
"isCat": false,
"token": "2Hw98d8KOCVR5v5g",
"emojis": [
],
"isAdmin": true,
"avatarId": null,
"bannerId": null,
"featured": null,
"isLocked": false,
"username": "admin",
"avatarUrl": null,
"bannerUrl": null,
"createdAt": "2019-10-22T04:47:40.520Z",
"updatedAt": null,
"isSilenced": false,
"notesCount": 0,
"avatarColor": null,
"bannerColor": null,
"isModerator": false,
"isSuspended": false,
"sharedInbox": null,
"lastFetchedAt": null,
"followersCount": 1,
"followingCount": 0
},
"content": {
"id": "https://misskey.nagaseyami.com/4501c452-d879-45b3-b9f6-f7dbe67bda36",
"type": "Follow",
"actor": "https://misskey.nagaseyami.com/users/7z4xm8yw1v",
"object": "https://misskey.io/users/7rkrarq81i",
"@context": [
"https://www.w3.org/ns/activitystreams",
"https://w3id.org/security/v1",
{
"Hashtag": "as:Hashtag"
}
]
}
},
"name": "__default__",
"opts": {
"delay": 0,
"backoff": {
"type": "exponential",
"delay": 60000
},
"attempts": 8,
"timestamp": 1571720073520,
"removeOnFail": true,
"removeOnComplete": true
},
"delay": 0,
"progress": 0,
"timestamp": 1571720073520,
"finishedOn": null,
"stacktrace": [
"Error: Missing process handler for job type __default__ at Queue.processJob (/misskey/node_modules/bull/lib/queue.js:1034:7) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:93:5)"
],
"processedOn": 1571720073522,
"returnvalue": null,
"attemptsMade": 1,
"failedReason": "Missing process handler for job type __default__"
}
}
1分前 [api] Internal error occurred in following/create
{
"e": {
"code": "QueryFailedError",
"stack": "QueryFailedError: duplicate key value violates unique constraint "IDX_d54a512b822fac7ed52800f6b4" at new QueryFailedError (/misskey/node_modules/typeorm/error/QueryFailedError.js:11:28) at Query.callback (/misskey/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38) at Query.handleError (/misskey/node_modules/pg/lib/query.js:142:17) at Connection.connectedErrorMessageHandler (/misskey/node_modules/pg/lib/client.js:211:17) at Connection.emit (events.js:210:5) at Connection.EventEmitter.emit (domain.js:476:20) at Socket.<anonymous> (/misskey/node_modules/pg/lib/connection.js:126:12) at Socket.emit (events.js:210:5) at Socket.EventEmitter.emit (domain.js:476:20) at addChunk (_stream_readable.js:308:12) at readableAddChunk (_stream_readable.js:289:11) at Socket.Readable.push (_stream_readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:182:23)",
"message": "duplicate key value violates unique constraint "IDX_d54a512b822fac7ed52800f6b4""
},
"ep": "following/create",
"ps": {
"i": "2Hw98d8KOCVR5v5g",
"userId": "7z4xuz8w44"
}
}
```

**Comment by ghost** [comment]
docker-compose.yml
```
version: "3"

services:
  web:
    build: .
    restart: always
    links:
      - db
      - redis
#      - es
    ports:
      - "127.0.0.1:3001:3001"
    networks:
      - internal_network
      - external_network

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:11.2-alpine
    networks:
      - internal_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    networks:
#      - internal_network
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data

networks:
  internal_network:
    internal: true
  external_network:
```

**Comment by ghost** [comment]
docker.env
```
# db settings
POSTGRES_PASSWORD=$q$v1szWN^r98le
POSTGRES_USER=misskey
POSTGRES_DB=misskey
```

**Comment by ghost** [comment]
default.yml
```
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Misskey configuration
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

#   ┌─────┐
#───┘ URL └─────────────────────────────────────────────────────

# Final accessible URL seen by a user.
url: https://misskey.nagaseyami.com/

# ONCE YOU HAVE STARTED THE INSTANCE, DO NOT CHANGE THE
# URL SETTINGS AFTER THAT!

#   ┌───────────────────────┐
#───┘ Port and TLS settings └───────────────────────────────────

#
# Misskey supports two deployment options for public.
#

# Option 1: With Reverse Proxy
#
#                 +----- https://example.tld/ ------------+
#   +------+      |+-------------+      +----------------+|
#   | User | ---> || Proxy (443) | ---> | Misskey (3000) ||
#   +------+      |+-------------+      +----------------+|
#                 +---------------------------------------+
#
#   You need to setup reverse proxy. (eg. nginx)
#   You do not define 'https' section.

# Option 2: Standalone
#
#                 +- https://example.tld/ -+
#   +------+      |   +---------------+    |
#   | User | ---> |   | Misskey (443) |    |
#   +------+      |   +---------------+    |
#                 +------------------------+
#
#   You need to run Misskey as root.
#   You need to set Certificate in 'https' section.

# To use option 1, uncomment below line.
port: 3001    # A port that your Misskey server should listen.

# To use option 2, uncomment below lines.
#port: 443

#https:
#  # path for certification
# key: /etc/letsencrypt/live/nagaseyami.com/privkey.pem
# cert: /etc/letsencrypt/live/nagaseyami.com/fullchain.pem

#   ┌──────────────────────────┐
#───┘ PostgreSQL configuration └────────────────────────────────

db:
  host: db
  port: 5432

  # Database name
  db: misskey

  # Auth
  user: misskey
  pass: $q$v1szWN^r98le

  # Whether disable Caching queries
  #disableCache: false

  # Extra Connection options
  #extra:
    #ssl: true

#   ┌─────────────────────┐
#───┘ Redis configuration └─────────────────────────────────────

redis:
  host: redis
  port: 6379
  #pass: example-pass

#   ┌─────────────────────────────┐
#───┘ Elasticsearch configuration └─────────────────────────────

#elasticsearch:
#  host: es
#  port: 9200
#  pass: null

#   ┌───────────────┐
#───┘ ID generation └───────────────────────────────────────────

# You can select the ID generation method.
# You don't usually need to change this setting, but you can
# change it according to your preferences.

# Available methods:
# aid ... Short, Millisecond accuracy
# meid ... Similar to ObjectID, Millisecond accuracy
# ulid ... Millisecond accuracy
# objectid ... This is left for backward compatibility

# ONCE YOU HAVE STARTED THE INSTANCE, DO NOT CHANGE THE
# ID SETTINGS AFTER THAT!

id: 'aid'

#   ┌─────────────────────┐
#───┘ Other configuration └─────────────────────────────────────

# If enabled:
#  The first account created is automatically marked as Admin.
autoAdmin: true

# Whether disable HSTS
disableHsts: false

# Number of worker processes
clusterLimit: 1

# Job concurrency per worker
deliverJobConcurrency: 128;
inboxJobConcurrency: 16;

# IP address family used for outgoing request (ipv4, ipv6 or dual)
outgoingAddressFamily: ipv4

# Syslog option
#syslog:
#  host: localhost
#  port: 514

# Proxy for HTTP/HTTPS
#proxy: http://127.0.0.1:3128

# Proxy for SMTP/SMTPS
#proxySmtp: http://127.0.0.1:3128   # use HTTP/1.1 CONNECT
#proxySmtp: socks4://127.0.0.1:1080 # use SOCKS4
#proxySmtp: socks5://127.0.0.1:1080 # use SOCKS5
```
