### ISSUE TITLE
DockerHubへのアップロードをGitHub Actionsに移す?

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#6376]
## Summary

別に Circle CI で困ってないしそれでもいいという説はある (高頻度でリリースするわけでもないからCircleCIの時間制限にもひっかからなさそうだし) ので要検討

やるなら @syuilo にDockerHubのトークンをGitHub Actionsのsecretsに指定してもらう必要がある

**Comment by rinsuki** [comment]
とりあえず GitHub Packages には GitHub Actionsで上げて、よさそうだったら DockerHub に上げるようにするという手もアリだと思う

**Comment by acid-chicken** [comment]
~~secret 自分持ってる~~って持ってるだけじゃ意味ないか

**Comment by acid-chicken** [comment]
若干オフトピだけど、とりあえず Docker Hub のアカウント持ってる Collaborator 各位アカウント教えてくださったら招待送ります。

**Comment by mei23** [comment]
今はDockerHub側でビルドしているのでもう不要？

**Comment by rinsuki** [comment]
一ヶ月前から止まってる… https://hub.docker.com/r/misskey/misskey/builds?page=1

**Comment by rinsuki** [comment]
あと DockerHub のビルド基本的に遅い (GitHub Actions 比) ~し Docker 社お金ないので~ GitHub Actions でビルドしたほうがいいかなという気はする

**Comment by mei23** [comment]
ん、今のDockerHubのは誰がビルドしてるのだわ？

**Comment by rinsuki** [comment]
普通に Circle CI がやってそう https://app.circleci.com/pipelines/github/misskey-dev/misskey/25090/workflows/f41855fd-4037-448e-948f-72915146a05b/jobs/9767

**Comment by syuilo** [comment]
今Stop buildingしたからもうされなくなるはず

**Comment by rinsuki** [comment]
- Circle CI が latest と 12.x.x タグをビルドしている
- DockerHub が latest と develop タグをビルドしている (しかし一ヶ月前から止まっている)

**Comment by rinsuki** [comment]
なので Circle CI 止めたらこのissueの内容をやらないといけない

**Comment by acid-chicken** [comment]
> 一ヶ月前から止まってる… https://hub.docker.com/r/misskey/misskey/builds?page=1

![image](https://user-images.githubusercontent.com/20679825/131209833-b4fab236-36fb-4549-a0c9-37d65adea1c0.png)

**Comment by rinsuki** [comment]
草

**Comment by acid-chicken** [comment]
https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

**Comment by mei23** [comment]
~~やっぱり Docker 社お金ないので~~
悪用起因なのね

**Comment by acid-chicken** [comment]
https://www.docker.com/community/open-source/application

ここに申請すればいいらしいけど、別に GitHub Actions でやれば良くね感はある

**Comment by mei23** [comment]
GitHub Actions でやってた方がわかりやすくてうれしい

**Comment by syuilo** [comment]
もう
https://github.com/misskey-dev/misskey/tree/develop/.circleci
要らない？

**Comment by rinsuki** [comment]
それが #7116

**Comment by tamaina** [comment]
あっ

**Comment by tamaina** [comment]
あら

**Comment by tamaina** [comment]
Action作るまではCircle CI復活させたらどうかしら

**Comment by syuilo** [comment]
Action作る

**Comment by syuilo** [comment]
ここ見れば良いかしら
https://docs.docker.jp/engine/userguide/dockerrepos.html

**Comment by syuilo** [comment]
こうかな
```yml
name: Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.9.0
      - name: Install dependencies
        run: yarn install
      - name: Copy Configure
        run: cp .circleci/misskey/*.yml .config
      - name: Build
        run: yarn build
      - name: Push to Docker Hub
        run: docker push misskey/misskey

```

**Comment by syuilo** [comment]
これ使って試せば良いか
https://vlike-vlife.netlify.app/posts/testtool_act

**Comment by mei23** [comment]
このへん？
https://docs.github.com/ja/actions/guides/publishing-docker-images

タグ付け
https://github.com/docker/metadata-action

**Comment by syuilo** [comment]
こうかな
```yml
name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: misskey/misskey
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
