### ISSUE TITLE
pope UI:一部画面にサイドの余白がない

### ISSUE THREAD

**Issue by futchitwo** [misskey-dev/misskey#7449]
## 💡 Summary

一部ページのメインコンテンツが左右いっぱいに引き伸ばされて余白がなくなる

![image](https://user-images.githubusercontent.com/74236683/114952226-d02cac80-9e90-11eb-83bd-efd07d5eb63b.png)

## 🙂 Expected Behavior

余白が表示される

## ☹️ Actual Behavior

余白が表示されず、メインコンテンツが左右いっぱいに広がる

## 📝 Steps to Reproduce

pope UI で以下の画面を開く：
ハイライト
検索
おしらせ
お気に入り
クリップ
Pages
アンテナ
見つける
リスト
グループ
あなた宛て
ダイレクト投稿
チャンネル
リバーシ（元の画面を覚えていないので前から余白がない可能性もある）
MFMチートシート

## 📌 Environment

Misskey　12.76.1

**Comment by futchitwo** [comment]
CSSの`_root`の内容を丸々`_section`に乗せ換えたらまずいかな
表示がおかしくないページ（タイムラインなど）では新UIが追加されたタイミングで`_section`が`_root`に置き換えられたっぽい(?)けどなぜなんだろう

**Comment by futchitwo** [comment]
余白問題はカスタムCSSでだいたいの応急処置ができる
```css
/* fix pope UI */

/** mwysmxbg: mfm-playground **/
._section,.mwysmxbg {
    box-sizing: border-box;
    margin: var(--root-margin,32px) auto;
    margin-top: calc(var(--root-margin, 32px) - 1px);
    max-width: min(var(--baseContentWidth),calc(100% - var(--root-margin, 32px)*2));
    padding-top: 1px;
}

/** lznhrdub: find **/
/** xprsixdl: garary **/
.lznhrdub[data-v-2aa57f3c],.xprsixdl[data-v-28eda414] {
  max-width: min(var(--baseContentWidth),calc(100% - var(--root-margin, 32px)*2)) !important;
}
```
ただ、ダイレクト投稿ページには`_root`も`_section`もないからCSSだけでは対処できない

あと上のCSSではギャラリーにも`max-width`を追加したけどこれはいらないかも
